#!/usr/bin/env R
# Mon Jun 28 23:48:00 2021
# Boyuan_Li


command=matrix(c(
	"Path", "p", "1", "character", 'The path you want to save file',
	"Fold", "f", "1", "numeric", 'the fold change you want to select the diff peak, this number will be log2 transform inside the script',
	"File", "i", "1", "character", 'the diff peak file produced by diffbind',
	"Name", "n", "1", "character" ,'the output file name'
	),byrow=T,ncol=5)


args=getopt::getopt(command)


if (is.null(args$Path) || is.null(args$Fold) || is.null(args$File) || is.null(args$Name)) {
	cat(paste(getopt::getopt(command, usage = T), "\n"))
	q()
}

#--- this script is used to do the go analysis for the result generated by diffbind, you can set the Foldchange cut off
path <- args$Path
fold <- log2(args$Fold)
file <- args$File
name <- args$Name
setwd(path)
suppressMessages(library(ChIPseeker))
suppressMessages(library(org.Mm.eg.db))
suppressMessages(library(clusterProfiler))
suppressMessages(library(TxDb.Mmusculus.UCSC.mm10.knownGene))
suppressMessages(library(ReactomePA))
suppressMessages(library(dplyr))
suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
suppressMessages(library(GenomicRanges))
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
data <- read.csv(file,stringsAsFactors = F,row.names = 1,header = T)
data <- na.omit(data)
up <- data[(data$log2FoldChange >= fold & data$padj<= 0.05),]
down <- data[(data$log2FoldChange <= -fold & data$padj<= 0.05),]


getvalue <- function(v){
  va <- eval(parse(text=v))
  return(va)
}
GO_fun <- function(data_ez,name){
  # browser()
  pathway_data <- enrichPathway(unique(data_ez$geneId),organism = 'mouse',pvalueCutoff = 1,qvalueCutoff = 1)
  # head(pathway_data, 2)
  n <- nrow(pathway_data@result)
  if (n > 15){
    l.num <- 15
  }else if (n>7){
    l.num <- n
  }else{
    l.num <- 7
  }
  tmp <- head(pathway_data@result,15)
  rt <- tmp$GeneRatio
  rt <- unlist(lapply(rt, getvalue))
  min <- min(rt)
  max <- max(rt)
  if ((max-min)==0){
    al <- 0.13
  }else{
    al <- (max-min)
  }
  fix <- al/(7/15*l.num)
  # pdf(paste0(name,'clust',i,'_enrich.pdf'),width = 9.5,height = 5)
  print(dotplot(pathway_data, showCategory=15)+coord_fixed(fix))
  ggsave(paste0(name,'_Reactome_enrich.pdf'),height = 5,width = 20)
  #print(plot)
  # dev.off()
  pathway_data <- setReadable(pathway_data, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
  fwrite(pathway_data@result,paste0(name,'_ReactomePA.txt'),sep = '\t')
  
  ego_data <- enrichGO(gene         = unique(data_ez$geneId),
                       OrgDb         = org.Mm.eg.db,
                       keyType       = 'ENTREZID',
                       ont           = "BP",
                       pAdjustMethod = "BH",
                       pvalueCutoff  = 1,
                       qvalueCutoff  = 1)
  ego_data <- setReadable(ego_data, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
  n <- nrow(ego_data@result)
  # browser()
  if (n > 15){
    l.num <- 15
  }else if (n>7){
    l.num <- n
  }else{
    l.num <- 7
  }
  
  tmp <- head(ego_data@result,15)
  rt <- tmp$GeneRatio
  rt <- unlist(lapply(rt, getvalue))
  min <- min(rt)
  max <- max(rt)
  if ((max-min)==0){
    al <- 0.13
  }else{
    al <- (max-min)
  }
  fix <- al/(7/15*l.num)
  # pdf(paste0(name,'clust',i,'_GO_BP_enrichment.pdf'),width = 9,height = 5)
  print(dotplot(ego_data, showCategory=15)+coord_fixed(fix))
  ggsave(paste0(name,'_GO_BP_enrichment.pdf'),height = 5,width = 20)
  # dev.off()
  fwrite(ego_data@result,paste0(name,'ego_clust_GO.txt'),sep = '\t')
  
  kegg_data <- enrichKEGG(gene         = unique(data_ez$geneId),
                          organism        = 'mmu',
                          keyType       = 'ncbi-geneid',
                          pAdjustMethod = "BH",
                          pvalueCutoff  = 1,
                          qvalueCutoff  = 1)
  kegg_data <- setReadable(kegg_data, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
  n <- nrow(kegg_data@result)
  if (n > 15){
    l.num <- 15
  }else if (n>7){
    l.num <- n
  }else{
    l.num <- 7
  }
  tmp <- head(kegg_data@result,15)
  rt <- tmp$GeneRatio
  rt <- unlist(lapply(rt, getvalue))
  min <- min(rt)
  max <- max(rt)
  if ((max-min)==0){
    al <- 0.13
  }else{
    al <- (max-min)
  }
  fix <- al/(7/15*l.num)
  # pdf(paste0(name,'_kegg_BP',i,'_enrichment.pdf'),width = 9,height = 5)
  print(dotplot(kegg_data, showCategory=15)+coord_fixed(fix))
  ggsave(paste0(name,'_kegg_enrichment.pdf'),height = 5,width = 20)
  # dev.off()
  # pdf(paste0(name,'bar_kegg_BP',i,'_enrichment.pdf'),width = 9,height = 5)
  # print(barplot(kegg_data, showCategory=15))
  # dev.off()
  fwrite(kegg_data@result,paste0(name,'kegg_GO.txt'),sep = '\t')
}


if (nrow(up)>0){
  up_gene <- bitr(rownames(up), fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Mm.eg.db")
  colnames(up_gene) <- c('gene','geneId')
  
  GO_fun(up_gene,paste0(name,'_up'))
}

if (nrow(down)>0){
  down_gene <- bitr(rownames(down), fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Mm.eg.db")
  colnames(down_gene) <- c('gene','geneId')
  
  GO_fun(down_gene,paste0(name,'_down'))
}

