#!/usr/bin/env R
# Mon Jun 28 23:48:00 2021
# Boyuan_Li


command=matrix(c(
	"Path", "p", "1", "character", 'The path you want to save file',
	"Fold", "f", "1", "numeric", 'the fold change you want to select the diff peak, this number will be log2 transform inside the script',
	"File", "i", "1", "character", 'the diff peak file produced by diffbind',
	"Name", "n", "1", "character" ,'the output file name'
	),byrow=T,ncol=5)


args=getopt::getopt(command)


if (is.null(args$Path) || is.null(args$Fold) || is.null(args$File) || is.null(args$Name)) {
	cat(paste(getopt::getopt(command, usage = T), "\n"))
	q()
}

#--- this script is used to do the go analysis for the result generated by diffbind, you can set the Foldchange cut off
path <- args$Path
fold <- log2(args$Fold)
file <- args$File
name <- args$Name
setwd(path)
suppressMessages(library(ChIPseeker))
suppressMessages(library(org.Mm.eg.db))
suppressMessages(library(clusterProfiler))
suppressMessages(library(TxDb.Mmusculus.UCSC.mm10.knownGene))
suppressMessages(library(ReactomePA))
suppressMessages(library(dplyr))
suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
suppressMessages(library(GenomicRanges))
suppressMessages(library(GOplot))
suppressMessages(library(ggsci))
suppressMessages(library(qpdf))
suppressMessages(library(stringr))
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
data <- fread(file)
if (ncol(data)==16){
  data <- fread(file,header = T,select = c(1:12)) %>% as.data.frame()
}else {
  data <- read.table(file,stringsAsFactors = F,row.names = 1,header = T)
}
data$FDR[is.na(data$FDR)] <- 0
up <- data[(data$Fold >= fold & data$FDR<= 0.05),]
down <- data[(data$Fold <= -fold & data$FDR<= 0.05),]

getgeneofpeak <- function(df){
  gr <- GenomicRanges::makeGRangesFromDataFrame(df)
  # gene <- seq2gene(gr, tssRegion = c(-2000, 2000), flankDistance = 3000, TxDb=txdb)
  peakAnno <- annotatePeak(gr, tssRegion=c(-2000, 2000),
                           TxDb=txdb, annoDb="org.Mm.eg.db",#overlap = 'TSS',
                           verbose=FALSE,addFlankGeneInfo=TRUE,
                           flankDistance=5000)
  peakAnno <- as.data.frame(peakAnno)
  
  return(peakAnno)
}

getvalue <- function(v){
  va <- eval(parse(text=v))
  return(va)
}
draw_centplot <- function(data){
  data@result <- data@result[order(data@result$p.adjust),][1:3,]
  cnetplot(data, circular = TRUE, colorEdge = TRUE)
}
GO_fun <- function(data_ez,name,gene.fold.pair){
  # browser()
  pathway_data <- enrichPathway(unique(data_ez$geneId),organism = 'mouse',pvalueCutoff = 1,qvalueCutoff = 1)
  # head(pathway_data, 2)
  get_fix <- function(data){
    n <- nrow(data@result)
    if (n > 15){
      l.num <- 15
    }else if (n>7){
      l.num <- n
    }else{
      l.num <- 7
    }
    tmp <- head(data@result,15)
    rt <- tmp$GeneRatio
    rt <- unlist(lapply(rt, getvalue))
    min <- min(rt)
    max <- max(rt)
    fix <- (max-min)/(7/15*l.num)
    return(fix)
  }
  fix <- get_fix(pathway_data)
  # pdf(paste0(name,'clust',i,'_enrich.pdf'),width = 9.5,height = 5)
  print(dotplot(pathway_data, showCategory=15)+coord_fixed(fix))
  ggsave(paste0(name,'_Reactome_enrich.pdf'),height = 5,width = 20)
  #print(plot)
  # dev.off()
  pathway_data <- setReadable(pathway_data, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
  fwrite(pathway_data@result,paste0(name,'_ReactomePA.txt'),sep = '\t')
  draw_centplot(pathway_data) + coord_fixed(1)
  ggsave(paste0(name,'_Reactome_centplot.pdf'),height = 5,width = 20)
  ego_data <- enrichGO(gene         = unique(data_ez$geneId),
                       OrgDb         = org.Mm.eg.db,
                       keyType       = 'ENTREZID',
                       ont           = "BP",
                       pAdjustMethod = "BH",
                       pvalueCutoff  = 1,
                       qvalueCutoff  = 1)
  ego_data <- setReadable(ego_data, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
  fix <- get_fix(ego_data)
  # pdf(paste0(name,'clust',i,'_GO_BP_enrichment.pdf'),width = 9,height = 5)
  print(dotplot(ego_data, showCategory=15)+coord_fixed(fix))
  ggsave(paste0(name,'_GO_BP_enrichment.pdf'),height = 5,width = 20)
  # dev.off()
  fwrite(ego_data@result,paste0(name,'ego_clust_GO.txt'),sep = '\t')
  draw_centplot(ego_data) + coord_fixed(1)
  ggsave(paste0(name,'_GO_BP_centplot.pdf'),height = 5,width = 20)
  kegg_data <- enrichKEGG(gene         = unique(data_ez$geneId),
                          organism        = 'mmu',
                          keyType       = 'ncbi-geneid',
                          pAdjustMethod = "BH",
                          pvalueCutoff  = 1,
                          qvalueCutoff  = 1)
  kegg_data <- setReadable(kegg_data, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
  fix <- get_fix(kegg_data)
  # pdf(paste0(name,'_kegg_BP',i,'_enrichment.pdf'),width = 9,height = 5)
  print(dotplot(kegg_data, showCategory=15)+coord_fixed(fix))
  ggsave(paste0(name,'_kegg_enrichment.pdf'),height = 5,width = 20)
  # dev.off()
  # pdf(paste0(name,'bar_kegg_BP',i,'_enrichment.pdf'),width = 9,height = 5)
  # print(barplot(kegg_data, showCategory=15))
  # dev.off()
  fwrite(kegg_data@result,paste0(name,'kegg_GO.txt'),sep = '\t')
  draw_centplot(kegg_data) + coord_fixed(1)
  ggsave(paste0(name,'_kegg_centplot.pdf'),height = 5,width = 20)
  circ <- trans2circ(pathway_data,'BP',gene.fold.pair)
  draw_GO(circ,paste0(name,'_ReactomePA'),gene.fold.pair,pathway_data)
  circ <- trans2circ(ego_data,'BP',gene.fold.pair)
  draw_GO(circ,paste0(name,'_GO'),gene.fold.pair,ego_data)
  circ <- trans2circ(kegg_data,'BP',gene.fold.pair)
  draw_GO(circ,paste0(name,'_Kegg'),gene.fold.pair,kegg_data)
}

pair.gene.fold <- function(data_assgn,data_peak){
  merge_data <- merge(data_assgn[,c(1:3,12,16)],data_peak[,c(1:3,9)],
                      by = c('seqnames','start','end'))
  data.out <- merge_data[,c(5:6)]
  data.out <- data.out %>% 
    dplyr::group_by(SYMBOL) %>% 
    dplyr::summarise(Fold = max(Fold)) %>%
    as.data.frame()
  return(data.out)
}

trans2circ <- function(ego_data,class,genedata){
  data <- ego_data
  if (nrow(data@result)>100){
    data@result <- data@result[order(data@result$p.adjust),][1:100,]
  }
  # tpm <- clusterProfiler::simplify(data,cutoff=0.7,by='p.adjust',select_fun=min)
  tpm <- data
  tpm <- setReadable(tpm, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
  GO <- tpm[1:15,c(1,2,8,6)]
  GO$geneID <- stringr::str_replace_all(GO$geneID,'/',',')
  names(GO) <- c('ID','Term','Genes','adj_pval')
  GO$Category <- class
  GO$ID <- GO$Term
  #--- diff gene
  genedata <- genedata
  names(genedata) <- c('ID','logFC')
  circ <- circle_dat(GO,genedata)
  return(circ)
}
source('/home/boyuanli/bashscript/bin/GO_analysis/GOplot_fun.r')
if (nrow(up)>0){
  up_gene <- getgeneofpeak(up)
  fwrite(up_gene,paste0(args$Name,'up_peak_coordgene.txt'),sep = '\t')
  up.gene.pair <- pair.gene.fold(up_gene,up)
  GO_fun(up_gene,paste0(name,'_up'),up.gene.pair)
}

if (nrow(down)>0){
  down_gene <- getgeneofpeak(down)
  fwrite(down_gene,paste0(args$Name,'down_peak_coordgene.txt'),sep = '\t')
  down.gene.pair <- pair.gene.fold(down_gene,down)
  GO_fun(down_gene,paste0(name,'_down'),down.gene.pair)
}

